spring:
  application:
    name: school # The name of the Spring Boot application

  datasource:
    url: jdbc:postgresql://localhost:5432/school_db # JDBC URL to connect to PostgreSQL; replace `school_db` with your database name
    username: postgres # PostgreSQL username
    password: root # PostgreSQL password
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: create # Controls how Hibernate manages the schema: `update`, `create`, `create-drop`, `validate`, or `none`
    show-sql: true # Enables SQL logging for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Hibernate dialect optimized for PostgreSQL
        format_sql: true # Formats SQL queries in the console for better readability
        use_sql_comments: true # Adds comments to SQL queries to indicate the source code line generating the query
        jdbc:
          lob:
            non_contextual_creation: true # Resolves potential issues with large object handling in PostgreSQL

  jackson:
    serialization:
      indent_output: true # Pretty-prints JSON responses for better readability
    default-property-inclusion: non_null # Excludes null values from JSON responses

  logging:
    level:
      root: info # Default log level
      org.springframework: debug # Enables debug logging for Spring components
    file:
      name: logs/school-application.log # Logs will be written to this file

  cache:
    type: none # Disables caching (useful for development); for production, set this to `simple`, `caffeine`, etc.

  profiles:
    active: dev # Sets the active Spring profile; useful for switching between `dev`, `test`, and `prod` configurations

server:
  port: 8080 # Defines the port where the application will run
  servlet:
    context-path: /api # Sets a base URL path for all endpoints, e.g., `http://localhost:8080/api`

management:
  endpoints:
    web:
      exposure:
        include: health,info # Exposes selected actuator endpoints
  health:
    db:
      enabled: true # Enables database health checks
